// <auto-generated />
using System;
using CentennialTalk.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentennialTalk.Persistence.Migrations
{
    [DbContext(typeof(ChatDBContext))]
    [Migration("20180809035637_QuestionsAdded")]
    partial class QuestionsAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CentennialTalk.Models.Discussion", b =>
                {
                    b.Property<Guid>("DiscussionId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DiscussionCode")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<bool>("IsLinkOpen");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("DiscussionId");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("CentennialTalk.Models.GroupMember", b =>
                {
                    b.Property<Guid>("GroupMemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChatCode")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ConnectionId");

                    b.Property<Guid?>("DiscussionId");

                    b.Property<bool>("IsConnected");

                    b.Property<bool>("IsModerator");

                    b.Property<DateTime>("JoiningTime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("GroupMemberId");

                    b.HasIndex("DiscussionId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("CentennialTalk.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChatCode")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<Guid?>("GroupMemberId");

                    b.Property<Guid>("RepliedMessageId");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime>("SentDate");

                    b.HasKey("MessageId");

                    b.HasIndex("GroupMemberId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CentennialTalk.Models.MessageReaction", b =>
                {
                    b.Property<Guid>("MessageReactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("MessageId");

                    b.Property<int>("ReactType");

                    b.Property<string>("Sender");

                    b.HasKey("MessageReactionId");

                    b.HasIndex("MessageId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("CentennialTalk.Models.QuestionModels.PollingQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<Guid?>("DiscussionId");

                    b.Property<bool>("IsPublished");

                    b.Property<bool>("SelectMultiple");

                    b.Property<int>("Type");

                    b.HasKey("QuestionId");

                    b.HasIndex("DiscussionId");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("CentennialTalk.Models.QuestionModels.QuestionOption", b =>
                {
                    b.Property<int>("OptionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid?>("PollingQuestionQuestionId");

                    b.Property<string>("Text");

                    b.HasKey("OptionId");

                    b.HasIndex("PollingQuestionQuestionId");

                    b.ToTable("QuestionOption");
                });

            modelBuilder.Entity("CentennialTalk.Models.QuestionModels.SubjectiveQuestion", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<Guid?>("DiscussionId");

                    b.Property<bool>("IsPublished");

                    b.Property<int>("Type");

                    b.HasKey("QuestionId");

                    b.HasIndex("DiscussionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CentennialTalk.Models.GroupMember", b =>
                {
                    b.HasOne("CentennialTalk.Models.Discussion")
                        .WithMany("Members")
                        .HasForeignKey("DiscussionId");
                });

            modelBuilder.Entity("CentennialTalk.Models.Message", b =>
                {
                    b.HasOne("CentennialTalk.Models.GroupMember")
                        .WithMany("Messages")
                        .HasForeignKey("GroupMemberId");
                });

            modelBuilder.Entity("CentennialTalk.Models.MessageReaction", b =>
                {
                    b.HasOne("CentennialTalk.Models.Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId");
                });

            modelBuilder.Entity("CentennialTalk.Models.QuestionModels.PollingQuestion", b =>
                {
                    b.HasOne("CentennialTalk.Models.Discussion")
                        .WithMany("Polls")
                        .HasForeignKey("DiscussionId");
                });

            modelBuilder.Entity("CentennialTalk.Models.QuestionModels.QuestionOption", b =>
                {
                    b.HasOne("CentennialTalk.Models.QuestionModels.PollingQuestion")
                        .WithMany("Options")
                        .HasForeignKey("PollingQuestionQuestionId");
                });

            modelBuilder.Entity("CentennialTalk.Models.QuestionModels.SubjectiveQuestion", b =>
                {
                    b.HasOne("CentennialTalk.Models.Discussion")
                        .WithMany("Questions")
                        .HasForeignKey("DiscussionId");
                });
#pragma warning restore 612, 618
        }
    }
}
