// <auto-generated />
using System;
using CentennialTalk.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentennialTalk.Persistence.Migrations
{
    [DbContext(typeof(ChatDBContext))]
    partial class ChatDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CentennialTalk.Models.Discussion", b =>
                {
                    b.Property<Guid>("DiscussionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiscussionCode")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<bool>("IsLinkOpen");

                    b.Property<DateTime>("LastUpdated");

                    b.Property<string>("ModeratorUsername")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("DiscussionId");

                    b.HasIndex("ModeratorUsername");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("CentennialTalk.Models.GroupMember", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255);

                    b.Property<string>("ChatCode")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("ConnectionId");

                    b.Property<Guid?>("DiscussionId");

                    b.Property<Guid>("GroupMemberId");

                    b.Property<bool>("IsConnected");

                    b.HasKey("Username");

                    b.HasIndex("DiscussionId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("CentennialTalk.Models.Message", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChatCode")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("GroupMemberUsername");

                    b.Property<string>("RepliedMessageId");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("MessageId");

                    b.HasIndex("GroupMemberUsername");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CentennialTalk.Models.Discussion", b =>
                {
                    b.HasOne("CentennialTalk.Models.GroupMember", "Moderator")
                        .WithMany()
                        .HasForeignKey("ModeratorUsername")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CentennialTalk.Models.GroupMember", b =>
                {
                    b.HasOne("CentennialTalk.Models.Discussion")
                        .WithMany("Members")
                        .HasForeignKey("DiscussionId");
                });

            modelBuilder.Entity("CentennialTalk.Models.Message", b =>
                {
                    b.HasOne("CentennialTalk.Models.GroupMember")
                        .WithMany("Messages")
                        .HasForeignKey("GroupMemberUsername");
                });
#pragma warning restore 612, 618
        }
    }
}
